export const ACCOUNTING_CAF_INPUT_BOOLEAN:string = 'BOOLEAN'
export const ACCOUNTING_CAF_INPUT_FREEFORM:string = 'FREE_FORM_TEXT'
export const ACCOUNTING_CAF_INPUT_SINGLE_CHOICE: string = 'SINGLE_CHOICE'

